import { Patient } from "./types";

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "p1",
    name: "A1",
    age: 45,
    gender: 'male',
    glucose: 110,
    A1Cresult: '>7',
    timeInHospital: 3,
    numMedications: 12,
    ejectionFraction: 45,
    serumCreatinine: 1.2,
    serumSodium: 138,
    highBloodPressure: true,
    smoking: false,
    cholesterol: 210,
    geneticMarkers: ["BRCA1"],
    steps: 8500,
    heartRate: 72,
    riskLevel: "medium",
    condition: "Type 2 Diabetes with moderate hypertension",
    personalizedMedicine: "Metformin 500mg (Standard), Lisinopril 10mg (ACE Inhibitor)",
    suggestedTreatmentPlan: "Daily glucose monitoring, low-sodium diet, 30 min brisk walking 5x/week",
    lastUpdated: "2024-03-01T10:00:00Z"
  },
  {
    id: "p2",
    name: "A2",
    age: 62,
    gender: 'female',
    glucose: 145,
    A1Cresult: '>8',
    timeInHospital: 7,
    numMedications: 24,
    ejectionFraction: 30,
    serumCreatinine: 1.8,
    serumSodium: 132,
    highBloodPressure: true,
    smoking: true,
    cholesterol: 190,
    geneticMarkers: ["APOE4"],
    steps: 3200,
    heartRate: 84,
    riskLevel: "high",
    condition: "Chronic Heart Failure with poor glycemic control",
    personalizedMedicine: "Entresto 24/26mg (ARNI), Jardiance 10mg (SGLT2 Inhibitor)",
    suggestedTreatmentPlan: "Strict fluid restriction (<1.5L/day), daily weight tracking, cardiac rehab program",
    lastUpdated: "2024-03-01T11:30:00Z"
  },
  {
    id: "p3",
    name: "A3",
    age: 34,
    gender: 'male',
    glucose: 95,
    A1Cresult: 'normal',
    timeInHospital: 1,
    numMedications: 4,
    ejectionFraction: 60,
    serumCreatinine: 0.8,
    serumSodium: 142,
    highBloodPressure: false,
    smoking: false,
    cholesterol: 160,
    geneticMarkers: [],
    steps: 12000,
    heartRate: 65,
    riskLevel: "low",
    condition: "Routine wellness checkup, healthy profile",
    personalizedMedicine: "No prescription required, Vitamin D3 2000IU daily",
    suggestedTreatmentPlan: "Maintain current active lifestyle, annual blood work for monitoring",
    lastUpdated: "2024-03-01T09:15:00Z"
  }
];

export const MOCK_RESEARCH_DATA = Array.from({ length: 50 }, (_, i) => ({
  id: `r${i}`,
  age: Math.floor(Math.random() * 60) + 20,
  glucose: Math.floor(Math.random() * 100) + 70,
  cholesterol: Math.floor(Math.random() * 150) + 150,
  ejectionFraction: Math.floor(Math.random() * 40) + 20,
  serumCreatinine: (Math.random() * 2 + 0.5).toFixed(1),
  drugResponse: Math.random() > 0.5 ? "Positive" : "Negative",
  geneticMarker: Math.random() > 0.7 ? "BRCA1" : "None"
}));
